# Site configuration
title: waqeen's site
description: waqeen cybersecurity 
url: https://waqeen.github.io
author: waqeen

# Build settings
markdown: kramdown
theme: minima

# Collections
collections:
  writeups:
    output: true
    permalink: /writeups/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_collections/_writeups"
      type: "writeups"
    values:
      layout: "writeup"

# Excluded files
exclude:
  - README.md
  - .gitignore
  - .github

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
